# Generated by Django 2.2.13 on 2021-07-08 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='GiftCard',
        ),
    ]
