# Generated by Django 2.2.13 on 2021-07-08 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_giftimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.GiftImages'),
        ),
    ]
